#!/bin/bash
set -x
export HOME=/home/theia
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

if [ -w /etc/passwd ]; then
  echo "${USER_ID}:x:$(id -u):0:${USER_ID} user:${HOME}:/sbin/nologin" >> /etc/passwd
fi
exec "$@"
