#!/bin/bash

DEFAULT_THEIA_RUNTIME_PATH="/home/theia/"
THEIA_RUNTIME_PATH=${THEIA_RUNTIME_PATH:-${DEFAULT_THEIA_RUNTIME_PATH}}
DEFAULT_THEIA_DIR="/opt/app-root/src"
THEIA_DIR=${THEIA_DIR:-${DEFAULT_THEIA_DIR}}
DEFAULT_THEIA_YARN_CMD="yarn theia start ${THEIA_DIR} --hostname 0.0.0.0"
THEIA_YARN_CMD=${THEIA_YARN_CMD:-${DEFAULT_THEIA_YARN_CMD}}

cd ${THEIA_RUNTIME_PATH}
${THEIA_YARN_CMD}
